<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
* Implements hook_theme().
*/
function intoto_crm_field_formatters_theme() {
  return array(
    'label_formatter' => array(
      'variables' => array('element' => NULL),
    ),
    'bootstrap_formatter' => array(
      'variables' => array('element' => NULL),
    ),
  );
}
	
	
/**
 * Implements hook_field_formatter_info().
 */
function intoto_crm_field_formatters_field_formatter_info() {
	return array(
		'intoto_label_formatter' => array( //Machine name of the formatter
			'label' => t('Small Label'),
			'field types' => array('text', 'text_long', 'text_with_summary', 'datetime', 'date', 'number_decimal', 'email', 'list_text', 'list_boolean'), //This will only be available to text fields
			'settings'	=> array( //Array of the settings we'll create
//				'pic_size' => 'small', //give a default value for when the form is first loaded
//				'tooltip' => 'Link to user Facebook page', //ditto
			),
		),

		'intoto_bootstrap_formatter' => array( //Machine name of the formatter
			'label' => t('Bootstrap'),
			'field types' => array('text', 'text_long', 'text_with_summary', 'datetime', 'date', 'number_decimal', 'email', 'list_text', 'list_boolean'), //This will only be available to text fields
			'settings'	=> array( //Array of the settings we'll create
//				'pic_size' => 'small', //give a default value for when the form is first loaded
//				'tooltip' => 'Link to user Facebook page', //ditto
			),
		),
	);
}


/**
 * Implements hook_field_formatter_settings_form().
 */
function intoto_crm_field_formatters_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
	//This gets the view_mode where our settings are stored
	$display = $instance['display'][$view_mode];
	//This gets the actual settings
	$settings = $display['settings'];
	return array();
/* this is an example of a facebook link button settings:
	//Initialize the element variable
		$element = array();
 
	//Add your select box
	$element['pic_size'] = array(
		'#type'					 => 'select',													 // Use a select box widget
		'#title'					=> t('Button Size'),									 // Widget label
		'#description'		=> t('Select what size of FB button'), // Helper text
		'#default_value'	=> $settings['pic_size'],							// Get the value if it's already been set
		'#options'				=> array(
			'small'	=> 'Small',
			'medium' => 'Medium',
			'large'	=> 'Large',
		),
	);
	$element['tooltip'] = array(
		'#type'					 => 'textfield',												// Use a textbox
		'#title'					=> t('Tool Tip'),											// Widget label
		'#description'		=> t('This text will appear when a user mouses over.'),	// helper text
		'#default_value'	=> $settings['tooltip'],							 // Get the value if it's already been set
	);
	return $element;
 
 */
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function intoto_crm_field_formatters_field_formatter_settings_summary($field, $instance, $view_mode) {
	return "";
	
	/* this is from the facebooklink example:
	$display = $instance['display'][$view_mode];
	$settings = $display['settings'];
	$summary = t('Use a @size Facebook button with the tooltip of "@tooltip"', array(
		'@size'		 => $settings['pic_size'],
		'@tooltip'	=> $settings['tooltip'],
	)); // we use t() for translation and placeholders to guard against attacks
	return $summary;
	 
	 */
}



 /*example from facebooklink:
/**
 * Implements hook_field_formatter_view().
 */
/*
 function facebooklink_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
	$element = array(); // Initialize the var
	$settings = $display['settings']; // get the settings
	$size = $settings['pic_size']; // The Size setting selected in the settings form
	$tooltip = $settings['tooltip']; // The tool tip assigned in settings
	// Create the image - Note that I'm storing the images in our module but they could be anywhere
	$image = '<img src="/' . drupal_get_path('module', 'facebooklink') . 'fb-' . $size . '.png">';
	foreach ($items as $delta => $item) {
		$fb = $item['safe_value']; // Getting the actual value
	}
	$options = array(
		'html'				=> TRUE, // This tells Drupal that we're sending HTML, not plain text, otherwise it would encode it
		'attributes'	=> array(
			'title' => $tooltip, // This sets our tooltip
			),
		);
	if(isset($fb)) {
		$link = l($image, $fb, $options); // Create the Link
		$element[0]['#markup'] = $link; // Assign it to the #markup of the element
	}
	return $element;
} 
 
 */
function intoto_crm_prepare_field_theme($theme, $entity_type, $entity, $field, $instance, $langcode, $items, $display) 
{
	$elements = array(); // Initialize the var
	$label_set = false;
//	drupal_set_message("items:<pre>".print_r($items, true)."</pre>");
//	drupal_set_message("field:<pre>".print_r($field, true)."</pre>");
//	drupal_set_message("instance:<pre>".print_r($instance, true)."</pre>");
	foreach ($items as $delta => $item) {
		$label = NULL;
		//print_r($display);
		$value = NULL;
		$comment = "";
		if (isset($item)){
			switch($field['type']){
				case 'email':
					$value = l($item['email'], 'mailto:' . $item['email'], array('absolute' => TRUE));
					break;
				case 'text_long':
					$value = $item['safe_value'];
					break;
				case 'datetime':
					$date = new DateTime($item['value']);
					$value = $date->format('Y-m-d');
					if ($field['field_name'] == 'field_date_of_birth')
					{
						$now = new DateTime('now');
						$interval = date_diff($now, $date);
						$comment .= $interval->format('%yyo');
						
					}
					break;
				case 'list_boolean':
				default :
					$value = $item['value'];
					break;

			}

			if (isset($field['settings']['allowed_values'][$value]))
			{
				$value = $field['settings']['allowed_values'][$value];
			}
			
			if (isset($instance['label']) && !$label_set) {  //!isset($label) because I want the label to appear only once
				$label = $instance['label'];
				$label_set = true;
			}
		}			
		$element = array('element' => $item, 'value' => $value, 'label' => $label, 'comment' => $comment, 'field' => $field, 'field_instance' => $instance, 'display' => $display);
		$elements[$delta] = array(
			'#markup' => theme($theme/*'label_formatter'*/, $element),
		);
	}

	return $elements;
}

function intoto_crm_field_formatters_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) 
{
//	$settings = $display['settings']; // get the settings
	//$size = $settings['pic_size']; // The Size setting selected in the settings form
	//$tooltip = $settings['tooltip']; // The tool tip assigned in settings
	// Create the image - Note that I'm storing the images in our module but they could be anywhere
	if ($display['type'] == 'intoto_label_formatter')
	{
		return intoto_crm_prepare_field_theme('label_formatter', $entity_type, $entity, $field, $instance, $langcode, $items, $display) ;
	}
	if ($display['type'] == 'intoto_bootstrap_formatter')
	{
		return intoto_crm_prepare_field_theme('bootstrap_formatter', $entity_type, $entity, $field, $instance, $langcode, $items, $display) ;
	}
}
			

/**
* Theme function for grasmash_formatter_grasmash_phone_mobile_call_link.
*/
function theme_label_formatter($element) {
	return '->>placeholder for element rendering in label_formatter theme<<-';// . $element['value'] . '<<-';//<a class="mobile-tel" href="tel:' . $element['element']['number']  . '">Call</a>';
}

function theme_bootstrap_formatter($element) {
	return '->>placeholder for element rendering in bootstrap_formatter theme<<-';// . $element['value'] . '<<-';//<a class="mobile-tel" href="tel:' . $element['element']['number']  . '">Call</a>';
}
