<?php

$module_name = 'intoto_crm';
module_load_include('inc', $module_name , 'tokens');
module_load_include('inc', $module_name , 'blocks');
module_load_include('inc', $module_name , 'forms');

module_load_include('inc', 'crm_core_relationship_ui', 'crm_core_relationship_ui.pages');


function intoto_crm_enable()
{
	variable_set('site_frontpage', 'home');
}
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function intoto_crm_help($path, $arg) {
  switch ($path) {
    case "admin/help#intoto_crm":
      return '<p>' . t("Implementation and hooks for Intoto") . '</p>';
      break;
  }
} 

function local_crm_core_relation_entity_ui_get_form_wrapper($contact, $type, $reverse) {
  return crm_core_relation_entity_ui_get_form_wrapper($contact, $type, $reverse);
}

function intoto_crm_menu()
{
	$items = array();    
	$items['crm-core/contact/%crm_core_contact/household/add'] = array(
		'title' => 'Add Household',
		'description' => 'Add a household to this contact',
//		'page callback' => 'crm_core_relation_entity_ui_get_form_wrapper',
		'page callback' => 'local_crm_core_relation_entity_ui_get_form_wrapper',

		'page arguments' => array( 2, "crm_member", "0"),
		'access callback' => 'crm_core_relationship_access_permissions',
		'access arguments' => array(NULL, 'create_view'),
//		'type' => MENU_LOCAL_ACTION,
		'type' => MENU_CALLBACK,
//		'file' => 'crm_core_relationship_ui.pages.inc',
	);
	return $items;
}

function intoto_crm_admin_paths_alter(&$paths) {
    $paths['crm-core/contact/*/household/add'] = TRUE;
    $paths['crm-core/contact/*/activity/add'] = TRUE;
    $paths['crm-core/contact/*/activity/add/comment'] = TRUE;
}

function intoto_crm_menu_alter(&$items)
{
	//unset($items['crm-core/contact/%crm_core_contact']);
	unset($items['crm-core/contact/%crm_core_contact/view']);
//	$items['crm-core/contact/%crm_core_contact/view'] = $items['crm-core/contact/%crm_core_contact/details'];
//	$items['crm-core/contact/%crm_core_contact/view']['type'] = MENU_CALLBACK;
//	$items['crm-core/contact/%crm_core_contact/details']['type'] = MENU_DEFAULT_LOCAL_TASK;
}


//function intoto_crm_entity_update($entity, $type)
//{
//	
////	$message = "XYZ";
////	drupal_set_message($message, /*$type*/ 'status', /*$repeat*/FALSE);
//}


function intoto_crm_entity_presave($entity, $type){
//function intoto_crm_entity_insert($entity, $type){
//	drupal_set_message("added entity of type $type:". $entity->type);
	//drupal_set_message("<pre>" . print_r($entity, true) . "</pre>");
	if (isset($type) && $type == "crm_core_contact"){
		try {		
			$contact_wrapper = entity_metadata_wrapper('crm_core_contact', $entity);
			if (isset($contact_wrapper->{"field_caption"}))
			{
				$caption = $contact_wrapper->{"field_caption"}->value();
	//			drupal_set_message("<pre>" . print_r($entity->contact_name, true) . "</pre>");
				$contact_wrapper->{"contact_name"}->{"given"}->set($caption);
	//			drupal_set_message("<pre>" . print_r($entity->contact_name, true) . "</pre>");
	//					->set(
	//						array(
	//								"title" => "",
	//								"given" => $caption,
	//								"middle" => "",
	//								"family" => "",
	//								"generational" => "",
	//								"credentials" =>  "",
	//							)
	//					);
	//			$contact_wrapper->contact_name_family ->set("");
			}
		}catch (EntityMetadataWrapperException $exc) {
			drupal_set_message("exception:" . $exc->getTraceAsString() );
			
		}
	}
}
