#!/bin/bash
USER=$1
PASS=$2
DB=$3

URL=mysql://$USER:$PASS@localhost/$DB


echo creating mysql db
echo enter root pwd
sudo mysql -hlocalhost -uroot -p -e "create database $DB; \
grant usage on *.* to $USER@localhost identified by '$PASS';
grant all privileges on $DB.* to $USER@localhost" || echo "failed to create db and user"

echo installing drupal site on $URL

drush si standard --db-url=$URL --site-name="Tammuz CRM Dev" --account-pass="12345" --site-mail="admin@tammuz-crm.com" install_configure_form.update_status_module='array(FALSE,FALSE)'
