; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.37"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[addressfield][version] = "1.1"

projects[ctools][version] = "1.7"

projects[cck_phone][version] = "1.x-dev"

projects[crm_core][version] = "development-dev"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[devel_themer][version] = "1.x-dev"

projects[email][version] = "1.3"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.5"

projects[field_group][version] = "1.4"

projects[homebox][version] = "2.0-rc1"

projects[link][version] = "1.3"

projects[name][version] = "1.9"

projects[relation][version] = "1.0-rc7"

projects[simplehtmldom][version] = "1.12"

projects[views][version] = "3.11"

; Themes
projects[bootstrap][version] = "3.0"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tammuz_crm][download][type] = ""
projects[tammuz_crm][download][url] = ""
projects[tammuz_crm][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tammuz_crm_feature][download][type] = ""
projects[tammuz_crm_feature][download][url] = ""
projects[tammuz_crm_feature][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[bootstrap_dashboard][download][type] = ""
projects[bootstrap_dashboard][download][url] = ""
projects[bootstrap_dashboard][type] = "theme"

