<?php
/**
 * @file
 * ormil_site_settings_entities.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function ormil_site_settings_entities_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_new_leads_notify_users'
  $field_bases['field_new_leads_notify_users'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_new_leads_notify_users',
    'indexes' => array(
      'target_id' => array(
        0 => 'target_id',
      ),
    ),
    'locked' => 0,
    'module' => 'entityreference',
    'settings' => array(
      'handler' => 'views',
      'handler_settings' => array(
        'behaviors' => array(
          'views-select-list' => array(
            'status' => 1,
          ),
        ),
        'view' => array(
          'args' => array(),
          'display_name' => 'entityreference_1',
          'view_name' => 'users',
        ),
      ),
      'profile2_private' => FALSE,
      'target_type' => 'user',
    ),
    'translatable' => 0,
    'type' => 'entityreference',
  );

  return $field_bases;
}
