<?php // 
//

function local_crm_core_relation_entity_ui_get_form_wrapper($contact, $type, $reverse) {
	return crm_core_relation_entity_ui_get_form_wrapper($contact, $type, $reverse);
}


function ormil_menu()
{
	$items = array();    
	$items['crm-core/contact/%crm_core_contact/household/add'] = array(
		'title' => 'Add Household',
		'description' => 'Add a household to this contact',
//		'page callback' => 'crm_core_relation_entity_ui_get_form_wrapper',
		'page callback' => 'local_crm_core_relation_entity_ui_get_form_wrapper',

		'page arguments' => array( 2, "crm_member", "0"),
		'access callback' => 'crm_core_relationship_access_permissions',
		'access arguments' => array(NULL, 'create_view'),
//		'type' => MENU_LOCAL_ACTION,
		'type' => MENU_CALLBACK,
//		'file' => 'crm_core_relationship_ui.pages.inc',
	);

	$items['crm-core/contact/%crm_core_contact/household_member/add'] = array(
		'title' => 'Add Household Member',
		'description' => 'Add a household member to this contact',
//		'page callback' => 'crm_core_relation_entity_ui_get_form_wrapper',
		'page callback' => 'local_crm_core_relation_entity_ui_get_form_wrapper',

		'page arguments' => array( 2, "crm_member", "1"),
		'access callback' => 'crm_core_relationship_access_permissions',
		'access arguments' => array(NULL, 'create_view'),
//		'type' => MENU_LOCAL_ACTION,
		'type' => MENU_CALLBACK,
//		'file' => 'crm_core_relationship_ui.pages.inc',
	);

	return $items;
}

function ormil_menu_alter(&$items)
{
	//print("in intoto_crm_menu_alter\n:".print_r(array_keys($items), true). "\n");
	//unset($items['crm-core/contact/%crm_core_contact']);
	unset($items['crm-core/contact/%crm_core_contact/view']);
//	unset($items['crm-core/contact/%crm_core_contact/edit']);
	$items['crm-core/contact/%crm_core_contact/edit']['type'] = MENU_CALLBACK;
	
	
//	$items['crm-core/contact/%crm_core_contact/view'] = $items['crm-core/contact/%crm_core_contact/details'];
//	$items['crm-core/contact/%crm_core_contact/view']['type'] = MENU_CALLBACK;
//	$items['crm-core/contact/%crm_core_contact/details']['type'] = MENU_DEFAULT_LOCAL_TASK;
}

function ormil_admin_paths_alter(&$paths) {
    $paths['crm-core/contact/*/household/add'] = TRUE;
    $paths['crm-core/contact/*/household_member/add'] = TRUE;
    $paths['crm-core/contact/*/activity/add'] = TRUE;
    $paths['crm-core/contact/*/activity/add/*'] = TRUE;
    $paths['crm-core/contact/*/edit'] = TRUE;
}

function ormil_views_api() {
  return array(
    'api' => 3,
  );
}


/**
* Implementation of hook_ctools_plugin_api().
*/
function ormil_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1); 
  }
}
