<?php // 

$module_name = 'tammuz';
module_load_include('inc', $module_name , 'blocks');
module_load_include('inc', $module_name , 'forms');

function local_crm_core_relation_entity_ui_get_form_wrapper($contact, $type, $reverse) {
	return crm_core_relation_entity_ui_get_form_wrapper($contact, $type, $reverse);
}


function tammuz_menu()
{
	$items = array();    
	$items['crm-core/contact/%crm_core_contact/household/add'] = array(
		'title' => 'Add Household',
		'description' => 'Add a household to this contact',
//		'page callback' => 'crm_core_relation_entity_ui_get_form_wrapper',
		'page callback' => 'local_crm_core_relation_entity_ui_get_form_wrapper',

		'page arguments' => array( 2, "member", "0"),
		'access callback' => 'crm_core_relationship_access_permissions',
		'access arguments' => array(NULL, 'create_view'),
//		'type' => MENU_LOCAL_ACTION,
		'type' => MENU_CALLBACK,
//		'file' => 'crm_core_relationship_ui.pages.inc',
	);

	$items['crm-core/contact/%crm_core_contact/household_member/add'] = array(
		'title' => 'Add Household Member',
		'description' => 'Add a household member to this contact',
//		'page callback' => 'crm_core_relation_entity_ui_get_form_wrapper',
		'page callback' => 'local_crm_core_relation_entity_ui_get_form_wrapper',

		'page arguments' => array( 2, "member", "1"),
		'access callback' => 'crm_core_relationship_access_permissions',
		'access arguments' => array(NULL, 'create_view'),
//		'type' => MENU_LOCAL_ACTION,
		'type' => MENU_CALLBACK,
//		'file' => 'crm_core_relationship_ui.pages.inc',
	);

	return $items;
}

function tammuz_menu_alter(&$items)
{
	//print("in intoto_crm_menu_alter\n:".print_r(array_keys($items), true). "\n");
	//unset($items['crm-core/contact/%crm_core_contact']);
	unset($items['crm-core/contact/%crm_core_contact/view']);
//	unset($items['crm-core/contact/%crm_core_contact/edit']);
	$items['crm-core/contact/%crm_core_contact/edit']['type'] = MENU_CALLBACK;
	unset ($items['crm-core/contact/%crm_core_contact/relationships/add']);
	
	
//	$items['crm-core/contact/%crm_core_contact/view'] = $items['crm-core/contact/%crm_core_contact/details'];
//	$items['crm-core/contact/%crm_core_contact/view']['type'] = MENU_CALLBACK;
//	$items['crm-core/contact/%crm_core_contact/details']['type'] = MENU_DEFAULT_LOCAL_TASK;
}


function tammuz_views_default_views_alter(&$views)
{

	if (isset($views['crm_activities_by_contact'])){
		$views['crm_activities_by_contact'] -> disabled = true;
	}
	if (isset($views['crm_relationships_by_contact']))
	{
		$views['crm_relationships_by_contact'] -> disabled = true;
	}
}

/**
* Implementation of hook_ctools_plugin_api().
*/
function tammuz_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1); 
  }
}


function tammuz_views_api() {
  return array(
    'api' => '2.0',
  );
}

/**
 * Implementation of hook_default_page_manager_pages().
 */
function tammuz_default_page_manager_pages() {
	$files = file_scan_directory(drupal_get_path('module', 'tammuz'). '/pages', '/.*inc.*/');
	foreach ($files as $absolute => $file) {
		$page = NULL; //prevent IDE editor warning on uninitialized var
		require $absolute;
		if (isset($page)) {
			$pages[$file->name] = $page;
		}   
	}
	return $pages;
}
